"""meals dinner many2many

Revision ID: 00034ea37afb
Revises: 13c7a47ad601
Create Date: 2019-12-16 11:54:41.895663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00034ea37afb'
down_revision = '13c7a47ad601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dinners_meals',
    sa.Column('dinner_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dinner_id'], ['dinners.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], )
    )
    op.drop_table('airports')
    op.add_column('meals', sa.Column('nutrition_value', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('vitamins', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('meals', 'vitamins')
    op.drop_column('meals', 'nutrition_value')
    op.create_table('airports',
    sa.Column('IATA_CODE', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('AIRPORT', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('CITY', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('STATE', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('COUNTRY', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('LATITUDE', sa.NUMERIC(precision=7, scale=5), autoincrement=False, nullable=True),
    sa.Column('LONGITUDE', sa.NUMERIC(precision=8, scale=5), autoincrement=False, nullable=True)
    )
    op.drop_table('dinners_meals')
    # ### end Alembic commands ###
