"""portion table

Revision ID: 598b8fa66f5c
Revises: 00034ea37afb
Create Date: 2019-12-16 14:33:20.029317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598b8fa66f5c'
down_revision = '00034ea37afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dinners_portions',
    sa.Column('dinner_id', sa.Integer(), nullable=True),
    sa.Column('portion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dinner_id'], ['dinners.id'], ),
    sa.ForeignKeyConstraint(['portion_id'], ['portions.id'], )
    )
    op.drop_table('dinners_meals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dinners_meals',
    sa.Column('dinner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dinner_id'], ['dinners.id'], name='dinners_meals_dinner_id_fkey'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name='dinners_meals_meal_id_fkey')
    )
    op.drop_table('dinners_portions')
    op.drop_table('portions')
    # ### end Alembic commands ###
